window.SAMPLE_VENUES = [
  {
    id: "sample-001",
    venueName: "SAMPLE BAR TOKYO",
    image: "../assets/venues/biz034-venue01-bartokyo-master-3x2-2400x1600@2x.jpg",
    images: ["../assets/venues/biz034-venue01-bartokyo-master-3x2-2400x1600@2x.jpg"],
    sampleNote: "（架空店舗・掲載イメージ）",
    category: "Cocktail Bar",
    country: "Japan",
    region: "Kanto",
    city: "Tokyo",
    address: "Shibuya, Tokyo（サンプルのため詳細住所は非表示）",
    descriptionJa:
      "落ち着いた雰囲気の中で、厳選したスピリッツとオリジナルカクテルをお楽しみいただけるカクテルバーです。カウンター越しの会話を大切に、初めての方にも入りやすい空間づくりを心がけています。",
    descriptionEn:
      "A quiet cocktail bar where you can enjoy carefully selected spirits and original cocktails. We value conversation across the counter and aim to create a space that feels easy to step into, even for first-time guests.",
    openingHours: "19:00–02:00（L.O. 01:30）",
    openingHoursEn: "19:00–02:00 (Last order 01:30)",
    ageRequirement: "20歳以上",
    ageRequirementEn: "20 years and older",
    languagesSupported: ["Japanese", "English"],
    website: "#sample-listing",
    priceInformation: "チャージ料金 ¥800（1名様）／セット料金 ¥3,500（ドリンク1杯+お通し）",
    priceInformationEn:
      "Cover charge ¥800 (per person) / Set price ¥3,500 (1 drink + a small starter)",
    priceTier: "¥¥",
    notes:
      "ドレスコードは特にございませんが、露出の多い服装・スポーツウェアはご遠慮いただく場合がございます。",
    notesEn:
      "There is no strict dress code, but we may kindly ask guests to avoid sportswear or overly revealing attire.",
    atmosphereStyle: ["落ち着いた", "大人向け"],
    atmosphereStyleEn: ["Quiet", "Adult-oriented"],
    features: ["カウンター席", "英語対応スタッフ", "禁煙"],
    featuresEn: ["Counter seating", "English-speaking staff", "Non-smoking"],
  },
  {
    id: "sample-002",
    venueName: "SAMPLE CLUB OSAKA",
    image: "../assets/venues/biz034-venue02-clubosaka-master-3x2-2400x1600@2x.jpg",
    images: ["../assets/venues/biz034-venue02-clubosaka-master-3x2-2400x1600@2x.jpg"],
    sampleNote: "（架空店舗・掲載イメージ）",
    category: "Nightclub",
    country: "Japan",
    region: "Kansai",
    city: "Osaka",
    address: "Namba, Osaka（サンプルのため詳細住所は非表示）",
    descriptionJa:
      "週末を中心にDJイベントを開催するナイトクラブです。フロアは広めで、国内外のDJによる音楽を楽しめます。入場時に身分証確認を行っています。",
    descriptionEn:
      "A nightclub hosting DJ events mainly on weekends. The dance floor is spacious, with music from both domestic and international DJs. ID verification is required at entry.",
    openingHours: "22:00–05:00（金・土のみ営業）",
    openingHoursEn: "22:00–05:00 (Fridays and Saturdays only)",
    ageRequirement: "20歳以上（要身分証提示）",
    ageRequirementEn: "20 years and older (ID required)",
    languagesSupported: ["Japanese", "English"],
    website: "#sample-listing",
    priceInformation: "入場料 ¥2,500（1ドリンク付）",
    priceInformationEn: "Admission ¥2,500 (includes 1 drink)",
    priceTier: "¥¥¥",
    notes: "20歳未満の方は入場をお断りしています。身分証をご持参ください。",
    notesEn: "Guests under 20 cannot be admitted. Please bring valid photo ID.",
    atmosphereStyle: ["賑やか", "音楽重視"],
    atmosphereStyleEn: ["Lively", "Music-focused"],
    features: ["クロークあり", "英語対応スタッフ", "喫煙エリアあり"],
    featuresEn: ["Coat check available", "English-speaking staff", "Smoking area available"],
  },
  {
    id: "sample-003",
    venueName: "SAMPLE JAZZ LOUNGE TOKYO",
    image: "../assets/venues/biz034-venue03-jazzloungetokyo-master-3x2-2400x1600@2x.jpg",
    images: ["../assets/venues/biz034-venue03-jazzloungetokyo-master-3x2-2400x1600@2x.jpg"],
    sampleNote: "（架空店舗・掲載イメージ）",
    category: "Live House / Jazz Lounge",
    country: "Japan",
    region: "Kanto",
    city: "Tokyo",
    address: "Roppongi, Tokyo（サンプルのため詳細住所は非表示）",
    descriptionJa:
      "生演奏のジャズを聴きながら食事とお酒を楽しめるラウンジです。落ち着いた照明と席間隔にこだわり、会話を楽しみたいお客様にも配慮しています。",
    descriptionEn:
      "A lounge where you can enjoy live jazz performances alongside food and drinks. We pay close attention to lighting and seating spacing so guests can comfortably enjoy conversation.",
    openingHours: "18:00–24:00（L.O. 23:00）",
    openingHoursEn: "18:00–24:00 (Last order 23:00)",
    ageRequirement: "20歳以上",
    ageRequirementEn: "20 years and older",
    languagesSupported: ["Japanese", "English", "Chinese"],
    website: "#sample-listing",
    priceInformation:
      "テーブルチャージ ¥1,000（1名様）／ライブ観覧料 別途¥1,500〜（公演により変動）",
    priceInformationEn:
      "Table charge ¥1,000 (per person) / Live performance fee from ¥1,500 (varies by show)",
    priceTier: "¥¥¥",
    notes: "演奏中の会話はお控えいただく場合があります。予約優先制です。",
    notesEn:
      "We may ask guests to keep conversation quiet during performances. Reservations are prioritized.",
    atmosphereStyle: ["落ち着いた", "音楽重視", "大人向け"],
    atmosphereStyleEn: ["Quiet", "Music-focused", "Adult-oriented"],
    features: ["生演奏あり", "英語対応スタッフ", "個室なし"],
    featuresEn: ["Live music", "English-speaking staff", "No private rooms"],
  },
  {
    id: "sample-004",
    venueName: "SAMPLE IZAKAYA NIGHT TOKYO",
    image: "../assets/venues/biz034-venue04-izakayanighttokyo-master-3x2-2400x1600@2x.jpg",
    images: ["../assets/venues/biz034-venue04-izakayanighttokyo-master-3x2-2400x1600@2x.jpg"],
    sampleNote: "（架空店舗・掲載イメージ）",
    category: "Night Dining / Izakaya",
    country: "Japan",
    region: "Kanto",
    city: "Tokyo",
    address: "Shinjuku, Tokyo（サンプルのため詳細住所は非表示）",
    descriptionJa:
      "旬の食材を使った和食と日本酒を楽しめる居酒屋です。メニューは写真付きで多言語表記に対応し、初めての方にも注文しやすい工夫をしています。",
    descriptionEn:
      "An izakaya serving seasonal Japanese dishes and sake. The menu includes photos and multilingual labels, making it easy for first-time guests to order.",
    openingHours: "17:00–23:30（L.O. 23:00）",
    openingHoursEn: "17:00–23:30 (Last order 23:00)",
    ageRequirement: "年齢制限なし（20歳未満のアルコール提供は不可）",
    ageRequirementEn: "No general age restriction (alcohol not served to guests under 20)",
    languagesSupported: ["Japanese", "English", "Korean"],
    website: "#sample-listing",
    priceInformation: "お通し料 ¥400（1名様）／平均予算 ¥3,000〜4,000（1名様）",
    priceInformationEn: "Table charge ¥400 (per person) / Average budget ¥3,000–4,000 (per person)",
    priceTier: "¥¥",
    notes: "個室は数に限りがあります。混雑時はご案内までお時間をいただく場合があります。",
    notesEn: "Private rooms are limited in number. During busy hours, seating may take extra time.",
    atmosphereStyle: ["賑やか", "カジュアル"],
    atmosphereStyleEn: ["Lively", "Casual"],
    features: ["多言語メニュー", "個室あり", "英語対応スタッフ"],
    featuresEn: ["Multilingual menu", "Private rooms available", "English-speaking staff"],
  },
  {
    id: "sample-005",
    venueName: "SAMPLE WINE BAR FUKUOKA",
    image: "../assets/venues/biz034-venue05-winebarfukuoka-master-3x2-2400x1600@2x.jpg",
    images: ["../assets/venues/biz034-venue05-winebarfukuoka-master-3x2-2400x1600@2x.jpg"],
    sampleNote: "（架空店舗・掲載イメージ）",
    category: "Wine Bar",
    country: "Japan",
    region: "Kyushu",
    city: "Fukuoka",
    address: "Tenjin, Fukuoka（サンプルのため詳細住所は非表示）",
    descriptionJa:
      "小規模ながら世界各国のワインを揃えるワインバーです。カウンター中心の造りで、スタッフとの会話を楽しみながら1杯から気軽に立ち寄れます。",
    descriptionEn:
      "A small wine bar offering a curated selection of wines from around the world. With counter-focused seating, guests can casually drop in for a single glass while chatting with staff.",
    openingHours: "18:00–01:00（L.O. 00:30）",
    openingHoursEn: "18:00–01:00 (Last order 00:30)",
    ageRequirement: "20歳以上",
    ageRequirementEn: "20 years and older",
    languagesSupported: ["Japanese", "English"],
    website: "#sample-listing",
    priceInformation: "グラスワイン ¥900〜／チャージ料金 ¥500（1名様）",
    priceInformationEn: "Glass of wine from ¥900 / Cover charge ¥500 (per person)",
    priceTier: "¥¥",
    notes: "席数が少ないため、事前のご連絡を推奨しています。",
    notesEn: "Seating is limited; contacting the venue in advance is recommended.",
    atmosphereStyle: ["落ち着いた", "カジュアル", "大人向け"],
    atmosphereStyleEn: ["Quiet", "Casual", "Adult-oriented"],
    features: ["カウンター席", "英語対応スタッフ", "禁煙"],
    featuresEn: ["Counter seating", "English-speaking staff", "Non-smoking"],
  },
  {
    id: "sample-006",
    venueName: "SAMPLE ROOFTOP BAR OSAKA",
    image: "../assets/venues/biz034-venue06-rooftopbarosaka-master-3x2-2400x1600@2x.jpg",
    images: ["../assets/venues/biz034-venue06-rooftopbarosaka-master-3x2-2400x1600@2x.jpg"],
    sampleNote: "（架空店舗・掲載イメージ）",
    category: "Rooftop Bar",
    country: "Japan",
    region: "Kansai",
    city: "Osaka",
    address: "Umeda, Osaka（サンプルのため詳細住所は非表示）",
    descriptionJa:
      "屋上の開放的な空間で夜景とお酒を楽しめるバーです。天候により屋内席へのご案内となる場合があります。",
    descriptionEn:
      "A rooftop bar where guests can enjoy the night view and drinks in an open-air setting. Depending on weather, guests may be seated indoors instead.",
    openingHours: "17:00–24:00（L.O. 23:30、季節により変動）",
    openingHoursEn: "17:00–24:00 (Last order 23:30, hours may vary by season)",
    ageRequirement: "20歳以上",
    ageRequirementEn: "20 years and older",
    languagesSupported: ["Japanese", "English", "Chinese"],
    website: "#sample-listing",
    priceInformation: "チャージ料金 ¥700（1名様）／シグネチャーカクテル ¥1,600〜",
    priceInformationEn: "Cover charge ¥700 (per person) / Signature cocktails from ¥1,600",
    priceTier: "¥¥¥",
    notes: "荒天時は屋外席のご利用を一時休止する場合があります。",
    notesEn: "Outdoor seating may be temporarily unavailable during inclement weather.",
    atmosphereStyle: ["開放的", "大人向け"],
    atmosphereStyleEn: ["Open-air", "Adult-oriented"],
    features: ["屋外席あり", "英語対応スタッフ", "夜景"],
    featuresEn: ["Outdoor seating", "English-speaking staff", "Night view"],
  },
  {
    id: "sample-007",
    venueName: "SAMPLE EVENT SPACE TOKYO",
    image: "../assets/venues/biz034-venue07-eventspacetokyo-master-3x2-2400x1600@2x.jpg",
    images: ["../assets/venues/biz034-venue07-eventspacetokyo-master-3x2-2400x1600@2x.jpg"],
    sampleNote: "（架空店舗・掲載イメージ）",
    category: "Night Event Space",
    country: "Japan",
    region: "Kanto",
    city: "Tokyo",
    address: "Ebisu, Tokyo（サンプルのため詳細住所は非表示）",
    descriptionJa:
      "音楽イベントや交流会など、夜間の貸切イベントに利用されるスペースです。開催内容はイベントごとに異なるため、事前に主催者へご確認ください。",
    descriptionEn:
      "A space used for private nighttime events such as music events and social gatherings. Content varies by event, so please check with the organizer in advance.",
    openingHours: "イベントにより異なる（例: 19:00–23:00）",
    openingHoursEn: "Varies by event (e.g. 19:00–23:00)",
    ageRequirement: "20歳以上（イベントにより異なる場合あり）",
    ageRequirementEn: "20 years and older (may vary by event)",
    languagesSupported: ["Japanese", "English"],
    website: "#sample-listing",
    priceInformation: "参加費はイベントにより異なります（例: ¥2,000〜3,500）",
    priceInformationEn: "Participation fee varies by event (e.g. ¥2,000–3,500)",
    priceTier: "¥¥",
    notes: "イベント詳細・参加条件は主催者の公式案内をご確認ください。",
    notesEn:
      "Please check the organizer's official information for event details and participation conditions.",
    atmosphereStyle: ["賑やか", "音楽重視"],
    atmosphereStyleEn: ["Lively", "Music-focused"],
    features: ["貸切イベント利用", "英語対応スタッフ"],
    featuresEn: ["Private event use", "English-speaking staff"],
  },
];
